### ISSUE TITLE
[Bug] ... wood pickaxes not mining properly

### ISSUE THREAD

**Issue by chainsawpenguin** [SuperMartijn642/SuperMartijn642sCoreLib#34]
**Version Info**
- Minecraft, ... 1.20
- Core Lib, ...

**Description of the Bug**
...doesn't let the wood pickaxes collect cobblestone.

**Steps to Reproduce**
...every time a stone is broken with a pickaxe, it just breaks dropping nothing. Looking at the pickaxe.json under the mineable folder its showing as empty. not sure if it should be listing the types o f blocks that this tool could break

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Are you sure that's caused by my core library, because that seems rather unlikely 🤔
Tags are additive, so unless `"replace": true` is specified  they simply add to the items specified by the datapacks before it. The main reason my core library includes the empty tag is to make sure the tag exists in versions before 1.17.

**Comment by SuperMartijn642** [comment]
Tested it now and, indeed, pickaxes work just fine and blocks drop the expected items with my core library installed.
