### ISSUE TITLE
[Crash] I have a problem with CoreLib and SpongeForge that crashes the server.

### ISSUE THREAD

**Issue by marcoastor** [SuperMartijn642/SuperMartijn642sCoreLib#44]
**Version Info**
- Minecraft, 1.12.2 (SpongeForge 7.4.7)
- Core Lib, 1.1.12

**Steps to Reproduce**
I have a SpongeForge server that works perfectly with many mods and when I go to put the CoreLib to use other mods like Connected Glass or Moving Elevators, it won't turn on.

**Crash report (~/logs/latest.log)**
[In this web you can find my crash report](https://mclo.gs/siOEaxD)

**Comment by SanderWxD** [comment]
Same issue here.

MC 1.12.2, Forge 2860, latest SpongeForge, both version 1.1.12 and 1.1.12a of CoreLib cause the crash.
Server runs fine on the 225 mods installed but crashes as soon as CoreLib is added.

[crash-2023-08-13_21.24.36-server.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12339516/crash-2023-08-13_21.24.36-server.txt)

**Comment by SuperMartijn642** [comment]
It seems SpongeForge is using a bunch of unnecessary `@Overwrite` mixins instead of `@Inject`, making it almost impossible for others to inject into any methods overwritten by SpongeForge. Nonetheless, I have now added workarounds for any of the methods overwritten by SpongeForge which my core library also injects into.

Version 1.1.12b for Minecraft 1.12 should now be compatible with SpongeForge.
