### ISSUE TITLE
[Crash] 1.1.15 forge

### ISSUE THREAD

**Issue by Martini002** [SuperMartijn642/SuperMartijn642sCoreLib#52]
**Version Info**
- Minecraft, ... 1.20.2
- Core Lib, ... 1.1.15 forge

The game crash with just this mod installed supermartijn642corelib-1.1.15-forge-mc1.20.2 

**Crash report (~/logs/latest.log)**
https://hastebin.com/share/mepafudodu.php

**Comment by SuperMartijn642** [comment]
That link just leads to creating a new text upload 🤔

**Comment by Martini002** [comment]
> That link just leads to creating a new text upload 🤔

sorry, was my first time using that service
https://hastebin.com/share/orexovemar.markdown

**Comment by SuperMartijn642** [comment]
Are you sure that's the correct log? I see a bunch of other mods in there and no crash

**Comment by Martini002** [comment]
damn, let me reload the game with the core mod

**Comment by Martini002** [comment]
Here is, sorry for the wrong one..

https://hastebin.com/share/mepafudodu.php

**Comment by SuperMartijn642** [comment]
Hmm that seems like a Forge issue rather than something to do with my core library. I don't necessarily see anything in the change logs for newer Forge versions, but you could try updating Forge.

I will do some testing once I am at my computer again.

**Comment by Martini002** [comment]
I'm just 6 minor versions behind, is your library working with the latest version of forge?

**Comment by SuperMartijn642** [comment]
> I'm just 6 minor versions behind, is your library working with the latest version of forge?

I build my mod against the first version of Forge for 1.20.2, Forge 48.0.0. Unless Forge makes any breaking changes, it should work. However, there may always be bugs in Forge updates. Even if you are 'just 6 minor versions behind', something could have been fixed in there. Note that every Forge update is a minor version, thus minor vs major doesn't mean much.

I have looked around a bit in the Forge discord and it seems this is a Forge issue which affects multiple mods. The issue has not yet been resolved as it requires some intricate changes.
The parts affected by the issue aren't needed outside of the dev environment, so for the time being I have disabled them as a workaround.

The updated version is available as 1.1.15a for Forge on 1.20.2.
Thank you for reporting the issue!

**Comment by Martini002** [comment]
So, should I update to your latest build or should I downgrade to forge 48.0.0? Thank you

**Comment by Martini002** [comment]
Also, I have sent you a email last night, check it out please

**Comment by SuperMartijn642** [comment]
Update

**Comment by Martini002** [comment]
Seems good now, thank you!
